pid_file "~/.local/state/mpd/mpd.pid"
db_file "~/.local/share/mpd/mpd.db"
state_file "~/.local/state/mpd/mpdstate"
playlist_directory "~/.local/share/mpd/playlists"
bind_to_address "127.0.0.1"

music_directory "~/music"
follow_outside_symlinks "yes"

audio_output {
    type     "pipewire"
    name     "pipewire"
}

resampler {
  plugin "soxr"
  quality "very high"
}
