#!/usr/bin/env bash

DEPENDENCIES=(clipmenu)
for DEPENDENCY in "${DEPENDENCIES[@]}"; do
    type -p "$DEPENDENCY" &>/dev/null || {
        echo "error: Could not find '${DEPENDENCY}', is it installed?" >&2
        exit 1
    }
done

MENU_OPTS="$( $HOME/.config/scripts/dmenu-helper get_options )"

~/.config/scripts/polybar-helper disable >/dev/null 2>&1
trap "~/.config/scripts/polybar-helper enable >/dev/null 2>&1" EXIT

clipmenu $MENU_OPTS -p "   "
