#!/usr/bin/env sh

case "$1" in
    "install")
        if command -v bash > /dev/null 2>&1 && [ "$SHELL" != "$(command -v bash)" ]; then
            if [ "$PREFERRED_SHELL" = "bash" ]; then
                echo "Setting bash as default shell based on PREFERRED_SHELL"
                sudo usermod -s "$(command -v bash)" "$USER"
            elif [ -t 0 ] && [ -t 1 ]; then
                printf "Do you want to set the default shell to bash? [y/N] "
                read -r response
                if [ "$response" = "y" ]; then
                    sudo usermod -s "$(command -v bash)" "$USER"
                fi
            fi
        fi
        ;;
    "reinstall") ;;
    "uninstall") ;;
    *)
        echo "Unknown action: $1"
        exit 1
        ;;
esac
