#!/usr/bin/env sh
# shellcheck disable=SC2016

case "$1" in
    "install")
        if command -v zsh > /dev/null 2>&1 && [ "$SHELL" != "$(command -v zsh)" ]; then
            if [ "$PREFERRED_SHELL" = "zsh" ]; then
                echo "Setting zsh as default shell based on PREFERRED_SHELL environment variable"
                sudo usermod -s "$(command -v zsh)" "$USER"
            else
                read -r -p "Do you want to set the default shell to zsh? [y/N] " response
                if [ "$response" = "y" ]; then
                    sudo usermod -s "$(command -v zsh)" "$USER"
                fi
            fi
        fi
        echo "Adding ZDOTDIR to system-wide zshenv..."
        if [ -d "/etc/zsh" ]; then
            echo 'export ZDOTDIR="${HOME}/.config/zsh"' | sudo tee -a /etc/zsh/zshenv
        else
            echo 'export ZDOTDIR="${HOME}/.config/zsh"' | sudo tee -a /etc/zshenv
        fi
        ;;
    "reinstall") ;;
    "uninstall")
        echo "Removing ZDOTDIR from system-wide zshenv..."
        if [ -d "/etc/zsh" ]; then
            grep -v 'export ZDOTDIR="${HOME}/.config/zsh"' /etc/zsh/zshenv | sudo tee /etc/zsh/zshenv
        else
            grep -v 'export ZDOTDIR="${HOME}/.config/zsh"' /etc/zshenv | sudo tee /etc/zshenv
        fi
        ;;
    *)
        echo "Unknown action: $1"
        exit 1
        ;;
esac
