"""Aerospace member: generated borders.sh + relaunch."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from theme.components.base import Component, Effects
from theme.components.sketchybar import argb
from theme.helpers.logio import atomic_write, ok
from theme.palette import material_roles, slice_hash
from theme.resources.base import Context
from theme.state import make_record, read_member

BORDERS_SH = Path.home() / ".config/aerospace/borders.sh"

REQUIRED_ROLES = ("primary", "outline_variant")


def borders_script(active: str, inactive: str) -> str:
    return (
        "#!/bin/sh\n"
        "# generated by the theming system; do not edit\n"
        "pkill -x borders 2>/dev/null\n"
        "sleep 0.1\n"
        f"exec borders active_color={argb(active)} "
        f"inactive_color={argb(inactive)} width=2.0\n"
    )


class AerospaceComponent(Component):
    key = "aerospace"
    group = "macos"
    platform = "darwin"

    def consumed_slice(self, ctx: Context) -> dict[str, Any]:
        return {"roles": material_roles(ctx.palette, REQUIRED_ROLES)}

    def write_effects(self, ctx: Context) -> Effects:
        if ctx.dry_run:
            ok("aerospace: would rewrite borders.sh")
            return Effects()
        roles = material_roles(ctx.palette, REQUIRED_ROLES)
        script = borders_script(roles["primary"], roles["outline_variant"])
        BORDERS_SH.parent.mkdir(parents=True, exist_ok=True)
        atomic_write(BORDERS_SH, script)
        BORDERS_SH.chmod(0o755)
        ok("aerospace: borders.sh written")
        slice = {"active": roles["primary"], "inactive": roles["outline_variant"]}
        return Effects(
            reloads=[("borders", {})],
            record=(
                "macos",
                "aerospace",
                make_record(
                    slice_hash(self.consumed_slice(ctx)),
                    slice_hash(slice),
                    {},
                    {"borders_sh": {"state": "active"}},
                ),
            ),
        )

    def status(self, ctx: Context) -> int:
        from theme.helpers.logio import note_state

        old = read_member("macos", "aerospace")
        code = 0
        detail = None
        if not old or old.get("config_hash") != slice_hash(self.consumed_slice(ctx)):
            code |= 1
            detail = "no stamp or config changed"
        roles = material_roles(ctx.palette, REQUIRED_ROLES)
        if BORDERS_SH.exists():
            if BORDERS_SH.read_text() != borders_script(
                roles["primary"], roles["outline_variant"]
            ):
                code |= 2
                detail = "borders.sh stale vs palette"
        else:
            code |= 2
            detail = "borders.sh missing"
        note_state(self.group, self.key, code, detail)
        return code

    def build(self, ctx: Context) -> dict[str, Any]:
        return {}
