#!/usr/bin/env bash

#          _           _           _
#  ___ _ _| |_ ___ ___| |_ ___ ___| |_
# | .'| | |  _| . |_ -|  _| .'|  _|  _|
# |__,|___|_| |___|___|_| |__,|_| |_|

# load colors
xrdb -load ~/.config/X11/.Xresources &
# restore the wallpaper
nitrogen --restore &
# launch compositor
picom --experimental-backends &
# launch notification daemon
~/.config/scripts/dunst-start.sh &
# launch music player server
mopidy &
# launch clipboard manager
clipmenud &
# launch screen autolocker
light-locker &
# launch polkit agent for user authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# launch system bars
~/.config/scripts/polybar-start.sh &
# launch unclutter to hide cursor when inactive
unclutter &
# launch kunst to grab album art on play and notify on song change
~/.config/scripts/kunst-mod.sh --notify &
# set numlock key to off
numlockx off &
