#!/usr/bin/env sh

#          _           _           _
#  ___ _ _| |_ ___ ___| |_ ___ ___| |_
# | .'| | |  _| . |_ -|  _| .'|  _|  _|
# |__,|___|_| |___|___|_| |__,|_| |_|

# setup monitors using script if available
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/wm/current_layout" ]; then
    "${XDG_CONFIG_HOME:-$HOME/.config}"/wm/layouts/"$( cat "${XDG_CONFIG_HOME:-$HOME/.config}/wm/current_layout" )" &
fi
# check the DPI of the current monitors and set accordingly using the set-dpi script (if available)
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/wm/set-dpi" ]; then
    ${XDG_CONFIG_HOME:-$HOME/.config}/wm/set-dpi
fi
# restore the wallpaper
setbg &
# launch compositor
picom --experimental-backends &
# launch notification daemon
dunst-start &
# launch music player server
mopidy &
# launch clipboard manager
clipmenud &
# launch screen autolocker
light-locker &
# launch polkit agent for user authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# launch system bars
polybar-start &
# launch unclutter to hide cursor when inactive
unclutter &
# set numlock key to off
numlockx off &
