#!/bin/sh

# _                                   _           _           _
#| |_ ___ ___ _ _ _ _____ ___ ___ _ _| |_ ___ ___| |_ ___ ___| |_
#| . |_ -| . | | | |     |___| .'| | |  _| . |_ -|  _| .'|  _|  _|
#|___|___|  _|_____|_|_|_|   |__,|___|_| |___|___|_| |__,|_| |_|
#        |_|

# load colors
xrdb -load ~/.config/X11/.Xresources &
# load keybindings
sxhkd &
# restore the wallpaper
nitrogen --restore &
# launch compositor
picom &
# launch system bars
~/.config/scripts/polybar-start.sh &
# launch notification daemon
~/.config/scripts/dunst-start.sh &
# launch music player server
mpd &
# launch clipboard manager
greenclip daemon &
# launch screen autolocker
light-locker &
# launch polkit agent for user authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# launch clean-fullscreen script
~/.config/scripts/clean-fullscreen.sh &
# launch unclutter to hide cursor when inactive
unclutter &
# launch kunst to grab album art on play and notify on song change
~/.config/scripts/kunst-mod.sh --notify &
