#!/bin/sh

# bspwm autostart script

# load colors
xrdb -load ~/.config/X11/.Xresources &
# load keybindings
sxhkd &
# restore the wallpaper
nitrogen --restore &
# launch compositor
picom --config ~/.config/picom/picom.conf &
# launch system bars
~/.config/scripts/polybar-start.sh &
# launch notification daemon
~/.config/scripts/dunst-start.sh &
# launch music player server
mpd ~/.config/mpd/mpd.conf &
# launch clipboard manager
greenclip daemon &
# launch screen autolocker
light-locker &
# launch polkit agent for user authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
