#!/bin/sh

# bspwm config

# launch the autostart script
~/.config/bspwm/autostart &

# default 10-workspace setup
bspc monitor -d I II III IV V VI VII VIII IX X

# default border width and window gap are good
bspc config border_width            2
bspc config window_gap              12

# behavior settings
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config focus_follows_pointer   false

# color settings
bspc config focused_border_color    "#1A1A1A"
bspc config active_border_color     "#1A1A1A"
bspc config normal_border_color     "#AAAAAA"
bspc config urgent_border_color     "#CC6666"
bspc config presel_feedback_color   "#1A1A1A"

# window-specific settings

# rules for windows that are supposed to float
bspc rule -a nitrogen               state=floating center=on
bspc rule -a Lxappearance           state=floating center=on
bspc rule -a "*:floating"           state=floating center=on
# specific rule for conky
bspc rule -a Conky                  sticky=on manage=off lower=on
# allow terminals to be launched on any workspace even if the default one for terminals is the first one
bspc rule -a urxvt                  follow=on
bspc rule -a termite                follow=on
bspc rule -a st                     follow=on
# prefer monocle (fullscreen) layout for certain workspaces
bspc desktop II -l monocle
bspc desktop VII -l monocle
# application-specific workspace assignments
bspc rule -a Firefox                desktop='^2' follow=on
bspc rule -a Iceweasel              desktop='^2' follow=on
bspc rule -a qutebrowser            desktop='^2' follow=on
bspc rule -a Sublime_text           desktop='^3' follow=on
bspc rule -a code                   desktop='^3' follow=on
bspc rule -a Neovim                 desktop='^3' follow=on
bspc rule -a Atom                   desktop='^3' follow=on
bspc rule -a Brackets               desktop='^3' follow=on
bspc rule -a Eclipse                desktop='^3' follow=on
bspc rule -a LightTable             desktop='^3' follow=on
bspc rule -a Ltbin                  desktop='^3' follow=on
bspc rule -a Gvim                   desktop='^3' follow=on
bspc rule -a Thunar                 desktop='^4' follow=on
bspc rule -a Pcmanfm                desktop='^4' follow=on
bspc rule -a Nautilus               desktop='^4' follow=on
bspc rule -a ranger                 desktop='^4' follow=on
bspc rule -a Gparted                desktop='^4' follow=on
bspc rule -a mpv                    desktop='^5' follow=on
bspc rule -a mplayer2               desktop='^5' follow=on
bspc rule -a Vlc                    desktop='^5' follow=on
bspc rule -a libreoffice            desktop='^6' follow=on
bspc rule -a qpdfview               desktop='^6' follow=on
bspc rule -a Zathura                desktop='^6' follow=on state=tiled
bspc rule -a Abiword                desktop='^6' follow=on
bspc rule -a Gimp                   desktop='^7' follow=on
bspc rule -a Gimp-2.8               desktop='^7' follow=on
bspc rule -a Pinta                  desktop='^7' follow=on
bspc rule -a Inkscape               desktop='^7' follow=on
bspc rule -a Handbrake              desktop='^7' follow=on
bspc rule -a TelegramDesktop        desktop='^8' follow=on
bspc rule -a "Syncthing GTK"        desktop='^8' follow=on
bspc rule -a Transmission-gtk       desktop='^8' follow=on
bspc rule -a Uget-gtk               desktop='^8' follow=on
bspc rule -a gotop                  desktop='^9' follow=on
