#!/usr/bin/env sh

# color settings
bspc config focused_border_color "#1A1A1A"
bspc config active_border_color "#1A1A1A"
bspc config normal_border_color "#AAAAAA"
bspc config urgent_border_color "#CC6666"
bspc config presel_feedback_color "#1A1A1A"
