#!/usr/bin/env sh

# color settings
bspc config focused_border_color "#808080"
bspc config active_border_color "#808080"
bspc config normal_border_color "#7f7f7f"
bspc config urgent_border_color "#ffb3b2"
bspc config presel_feedback_color "#9ccbfb"
