#!/usr/bin/env sh

# let border width be the same everywhere
bspc config border_width 2

# behavior settings
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer false
bspc config ignore_ewmh_focus true
bspc config automatic_scheme alternate
