#!/bin/sh
# theme.sh — regenerate colors_generated.lua from the canonical Material palette.
# GUI world: reads palette.json .active.colors (Material You roles), NOT base16.
# Emits ARGB literals (0xffRRGGBB) consumed by colors.lua's semantic layer.
# Atomic write; never fails inside hooks (keeps previous file on any problem).
set -eu

PALETTE="$HOME/.cache/theme/palette.json"
OUT_DIR="$HOME/.config/sketchybar"
OUT="$OUT_DIR/colors_generated.lua"
TMP="$OUT_DIR/.colors_generated.tmp.$$"
trap 'rm -f "$TMP"' EXIT INT TERM

command -v jq >/dev/null || { echo "theme.sh: jq missing — keeping previous colors" >&2; exit 0; }
[ -f "$PALETTE" ] || { echo "theme.sh: palette.json missing — keeping previous colors" >&2; exit 0; }

# Material roles required for a complete swap (colors.lua maps these semantically)
REQUIRED="surface surface_container_high outline primary on_surface_variant on_surface error tertiary inverse_primary on_primary_fixed tertiary_container outline_variant"
# Custom hue wheel (matugen config: [config.custom_colors])
REQUIRED="$REQUIRED red orange yellow lime green mint teal azure blue violet magenta rose"

# Emit every material role as  <role> = 0xffRRGGBB,
jq -r '.active.colors | to_entries[] | select(.value | type == "string" and startswith("#")) |
       "\(.key) = 0xff\(.value[1:7] | ascii_upcase),"' "$PALETTE" > "$TMP" 2>/dev/null \
  || { echo "theme.sh: palette parse failed — keeping previous colors" >&2; exit 0; }

# Gate: all required roles present before swapping in
MISSING=0
for role in $REQUIRED; do
    grep -q "^$role " "$TMP" || { echo "theme.sh: missing role $role — keeping previous colors" >&2; MISSING=1; }
done
[ "$MISSING" = "0" ] || exit 0

{
  echo "-- Auto-generated by theme.sh — do not edit manually"
  echo "-- Source: palette.json .active.colors (Material) — Generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "local with_alpha = function(color, alpha)"
  echo "  if alpha > 1.0 or alpha < 0.0 then return color end"
  echo "  return (color & 0x00ffffff) | (math.floor(alpha * 255.0) << 24)"
  echo "end"
  echo ""
  echo "return {"
  cat "$TMP"
  echo ""
  echo "  with_alpha = with_alpha,"
  echo "}"
} > "${TMP}.final"
mv -f "${TMP}.final" "$OUT"
rm -f "$TMP"   # success-path cleanup: the trap is cleared below, so rm here
trap - EXIT INT TERM
