#!/usr/bin/env sh

xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --mode 1920x1080 --rate 120.00 --pos 1920x0 --rotate normal --output VIRTUAL1 --off
