general {
    uid = "owntone"
    db_path = "/var/cache/owntone/songs3.db"
    db_backup_path = "/var/cache/owntone/songs3.bak"
    logfile = "/var/cache/owntone/owntone.log"
    loglevel = log
    ipv6 = yes
    cache_dir = "/var/cache/owntone"
    high_resolution_clock = yes
}

library {
    name = "My Music on %h"
    port = 3689
    directories = { "/srv/media" }
    follow_symlinks = true
    hide_singles = false
    radio_playlists = true
    name_library    = "Library"
    name_music      = "Music"
    name_movies     = "Movies"
    name_tvshows    = "TV Shows"
    name_podcasts   = "Podcasts"
    name_audiobooks = "Audiobooks"
    name_radio      = "Radio"
}

audio {
    nickname = "Computer"
    type = "pulseaudio"
}

spotify {
}

mpd {
}

sqlite {
    vacuum = yes
}

streaming {
}
