enabled = true
description = "Firefox browser configuration"
tags = ["gui", "browser", "x11", "wayland", "web"]
os = ["linux", "macos"]
arch = []
condition = ""

[ignore]
linux = ["Library"]
macos = ["^/\\.config/mozilla"]
