[flags]
hide_avg_cpu = false
dot_marker = false
rate = 1000
left_legend = false
current_usage = false
group_processes = true
case_sensitive = false
whole_word = false
regex = true
temperature_type = "celsius"
default_time_value = 60000
time_delta = 15000
default_widget_type = "proc"
default_widget_count = 1
basic = false
use_old_network_legend = false
hide_table_gap = true
disable_click = false
color = "default"
mem_as_value = false
tree = false

[colors]
table_header_color="White"
widget_title_color="White"
avg_cpu_color="LightYellow"
cpu_core_colors=["LightGreen", "LightCyan", "LightBlue", "LightMagenta", "LightRed", "Green", "Cyan", "Blue", "Magenta", "Red"]
ram_color="LightGreen"
swap_color="LightYellow"
rx_color="LightBlue"
tx_color="LightRed"
border_color="Black"
highlighted_border_color="Cyan"
text_color="Gray"
selected_text_color="Black"
selected_bg_color="LightCyan"
graph_color="White"
high_battery_color="Green"
medium_battery_color="Yellow"
low_battery_color="Red"


[[row]]
 ratio=40
 [[row.child]]
 type="cpu"
[[row]]
 ratio=30
 [[row.child]]
  ratio=3
  [[row.child.child]]
   type="disk"
  [[row.child.child]]
   type="temp"
 [[row.child]]
  ratio=4
  type="mem"
[[row]]
 ratio=30
 [[row.child]]
  ratio=4
  type="net"
 [[row.child]]
  ratio=6
  type="proc"
