[flags]
rate = "1s"
temperature_type = "celsius"
default_time_value = "60s"
time_delta = "15s"
default_widget_type = "proc"
default_widget_count = 1
basic = false
dot_marker = false
use_old_network_legend = false
disable_click = false
table_gap = "none"

[cpu]
hide_avg_cpu = false
left_legend = false

[processes]
current_usage = false
case_sensitive = false
whole_word = false
regex = true
default_tree = false
default_grouped = true
default_memory_value = false

[styles]
theme = "default"

[styles.cpu]
avg_entry_colour = "LightYellow"
cpu_core_colours = [
  "LightGreen",
  "LightCyan",
  "LightBlue",
  "LightMagenta",
  "LightRed",
  "Green",
  "Cyan",
  "Blue",
  "Magenta",
  "Red",
]

[styles.memory]
ram_colour = "LightGreen"
swap_colour = "LightYellow"

[styles.network]
rx_colour = "LightBlue"
tx_colour = "LightRed"

[styles.tables]
headers = { colour = "White" }

[styles.graphs]
graph_colour = "White"

[styles.widgets]
widget_title = { colour = "White" }
text = { colour = "Gray" }
selected_text = { colour = "Black", bg_colour = "LightCyan" }
border_colour = "DarkGray"
selected_border_colour = "Cyan"

[styles.battery]
high_battery_colour = "Green"
medium_battery_colour = "Yellow"
low_battery_colour = "Red"

[[row]]
ratio = 40
[[row.child]]
type = "cpu"
[[row]]
ratio = 30
[[row.child]]
ratio = 3
[[row.child.child]]
type = "disk"
[[row.child.child]]
type = "temp"
[[row.child]]
ratio = 4
type = "mem"
[[row]]
ratio = 30
[[row.child]]
ratio = 4
type = "net"
[[row.child]]
ratio = 6
type = "proc"
