"""GNU Stow wrapper for package management."""

import subprocess
from pathlib import Path
from typing import Optional

try:
    import tomllib
except ImportError:
    import tomli as tomllib

from .package import get_current_os, load_package_metadata


class StowError(Exception):
    """Exception raised for stow operations failures."""

    pass


IGNORE_PATTERN = "\\.package\\.toml$"

GENERATED_IGNORE_HEADER = (
    "# Generated by the dotfiles installer - do not edit; "
    "source: .package.toml [ignore] table"
)

BASELINE_SECTION_HEADER = (
    "# baseline (replicates stow built-in defaults - "
    "a package-local ignore file replaces them)"
)

# Verbatim copy of the __DATA__ section that GNU stow's Makefile appends to
# lib/Stow.pm.in to build @default_global_ignore_regexps (source:
# https://github.com/aspiers/stow default-ignore-list @ 0ebf4fb, identical to
# the installed stow 2.4.1). A package-local .stow-local-ignore file REPLACES
# this built-in list, so it must be restated or stow would stow VCS metadata
# into the target directory.
BASELINE_IGNORE_REGEXPS = r"""# Comments and blank lines are allowed.

RCS
.+,v

CVS
\.\#.+       # CVS conflict files / emacs lock files
\.cvsignore

\.svn
_darcs
\.hg

\.git
\.gitignore
\.gitmodules

.+~          # emacs backup files
\#.*\#       # emacs autosave files

^/README.*$
^/LICENSE.*$
^/COPYING
"""


def load_ignore_rules(pkg_path: Path, target_os: Optional[str]) -> list[str]:
    """Load the [ignore] rules for the target OS from a package manifest."""
    metadata_file = pkg_path / ".package.toml"
    metadata = load_package_metadata(pkg_path)
    ignore_table = metadata.get("ignore", {})
    if not isinstance(ignore_table, dict):
        return []
    os_name = target_os or get_current_os()
    rules = ignore_table.get(os_name, [])
    if not isinstance(rules, list) or not all(isinstance(r, str) for r in rules):
        raise StowError(
            f"{metadata_file}: 'ignore.{os_name}' must be a list of rule strings"
        )
    return list(rules)


def ignore_folding_preferred(pkg_path: Path) -> bool:
    """
    Return True when the manifest's [ignore] table opts into tree folding.

    A package whose rules prune whole TOP-LEVEL trees is fold-safe: stow
    evaluates ignore rules at the package root before any folding, so the
    foreign tree is dropped first and folding the rest cannot bypass it
    (firefox live-fire lesson). Per-file links are instead fragile for
    trees a running application writes into (stow -D/-S races with runtime
    file creation, leaving mixed trees). Reserved key [ignore] fold = true
    opts such a package out of the forced --no-folding; any other value,
    a missing key, or a malformed table keeps --no-folding.
    """
    metadata = load_package_metadata(pkg_path)
    ignore_table = metadata.get("ignore", {})
    if not isinstance(ignore_table, dict):
        return False
    return ignore_table.get("fold") is True


def prepare_local_ignore(pkg_path: Path, target_os: Optional[str]) -> bool:
    """
    Generate or clean up the package's .stow-local-ignore for a target OS.

    Returns True when manifest rules were written; the caller must then stow
    with --no-folding, because folded directories bypass file-level ignores
    (stow issue #131). When no rules apply, a stale generated file is removed
    only if its first line carries the generated-header marker; when rules
    apply, an existing file is overwritten only if it carries the same
    marker - user-authored files are never touched on either path. Write
    failures raise StowError so callers abort instead of stowing unfiltered
    trees.
    """
    ignore_file = pkg_path / ".stow-local-ignore"
    rules = load_ignore_rules(pkg_path, target_os)

    if not rules:
        if ignore_file.is_file():
            lines = []
            try:
                lines = ignore_file.read_text().splitlines()
            except OSError as e:
                raise StowError(f"Cannot read {ignore_file}: {e}")
            if lines and lines[0].strip() == GENERATED_IGNORE_HEADER:
                try:
                    ignore_file.unlink()
                except OSError as e:
                    raise StowError(f"Cannot remove stale {ignore_file}: {e}")
        return False

    # stow wraps with-slash ignore rules as (^|/)(rule)(/|$) and matches them
    # against "/"+subpath, so a rule anchored with a bare '^' (not '^/') can
    # never match - reject it instead of silently stowing the "ignored" tree.
    for rule in rules:
        if "/" in rule and rule.startswith("^") and not rule.startswith("^/"):
            raise StowError(
                f"{pkg_path.name}: ignore rule {rule!r} can never match "
                "(stow matches path rules against '/'+subpath; "
                "anchor with '^/' or drop the '^')"
            )

    if ignore_file.is_file():
        lines = []
        try:
            lines = ignore_file.read_text().splitlines()
        except OSError as e:
            raise StowError(f"Cannot read {ignore_file}: {e}")
        first_line = next((line.strip() for line in lines if line.strip()), "")
        if first_line != GENERATED_IGNORE_HEADER:
            raise StowError(
                f"{pkg_path.name}: refusing to overwrite user-authored "
                f".stow-local-ignore at {ignore_file}; fold its rules into "
                ".package.toml [ignore] and remove the file"
            )

    content = "\n".join(
        [
            GENERATED_IGNORE_HEADER,
            BASELINE_SECTION_HEADER,
            BASELINE_IGNORE_REGEXPS.rstrip("\n"),
            "",
            *rules,
            "",
        ]
    )
    try:
        ignore_file.write_text(content)
    except OSError as e:
        raise StowError(f"Cannot write {ignore_file}: {e}")
    return True


def is_stowed(
    pkg_path: Path,
    target: Path,
    pkg_name: str,
    target_os: Optional[str] = None,
) -> bool:
    """Check if a package is already stowed."""
    rules_active = prepare_local_ignore(pkg_path, target_os)
    argv = ["stow", "-n", "-v", "-t", str(target), f"--ignore={IGNORE_PATTERN}"]
    if rules_active and not ignore_folding_preferred(pkg_path):
        argv.append("--no-folding")
    argv.append(pkg_name)
    result = subprocess.run(
        argv,
        cwd=pkg_path.parent,
        capture_output=True,
        text=True,
    )
    output = result.stdout + result.stderr

    if "would cause conflicts" in output or "LINK:" in output:
        return False
    if not output.strip() or "WARNING: in simulation mode" in output:
        return True
    return False


def stow_install(
    pkg_path: Path,
    target: Path,
    pkg_name: str,
    target_os: Optional[str] = None,
) -> bool:
    """Install a package using stow."""
    rules_active = prepare_local_ignore(pkg_path, target_os)
    argv = ["stow", "-t", str(target), f"--ignore={IGNORE_PATTERN}"]
    if rules_active and not ignore_folding_preferred(pkg_path):
        argv.append("--no-folding")
    argv.append(pkg_name)
    result = subprocess.run(
        argv,
        cwd=pkg_path.parent,
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def stow_reinstall(
    pkg_path: Path,
    target: Path,
    pkg_name: str,
    target_os: Optional[str] = None,
) -> bool:
    """Reinstall a package using stow (with override)."""
    rules_active = prepare_local_ignore(pkg_path, target_os)
    argv = [
        "stow",
        "--override=.*",
        "-R",
        "-t",
        str(target),
        f"--ignore={IGNORE_PATTERN}",
    ]
    if rules_active and not ignore_folding_preferred(pkg_path):
        argv.append("--no-folding")
    argv.append(pkg_name)
    result = subprocess.run(
        argv,
        cwd=pkg_path.parent,
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def stow_uninstall(
    pkg_path: Path,
    target: Path,
    pkg_name: str,
    target_os: Optional[str] = None,
) -> bool:
    """Uninstall a package using stow."""
    rules_active = prepare_local_ignore(pkg_path, target_os)
    argv = ["stow", "-D", "-t", str(target), f"--ignore={IGNORE_PATTERN}"]
    if rules_active and not ignore_folding_preferred(pkg_path):
        argv.append("--no-folding")
    argv.append(pkg_name)
    result = subprocess.run(
        argv,
        cwd=pkg_path.parent,
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def stow_check(
    pkg_path: Path,
    target: Path,
    pkg_name: str,
    target_os: Optional[str] = None,
) -> dict:
    """
    Check package installation status and potential conflicts.

    Returns dict with:
        - installed: bool
        - can_install: bool
        - conflicts: list[str]
    """
    if is_stowed(pkg_path, target, pkg_name, target_os=target_os):
        return {"installed": True, "can_install": False, "conflicts": []}

    rules_active = prepare_local_ignore(pkg_path, target_os)
    argv = ["stow", "-n", "-v", "-t", str(target), f"--ignore={IGNORE_PATTERN}"]
    if rules_active and not ignore_folding_preferred(pkg_path):
        argv.append("--no-folding")
    argv.append(pkg_name)
    result = subprocess.run(
        argv,
        cwd=pkg_path.parent,
        capture_output=True,
        text=True,
    )

    output = result.stdout + result.stderr
    conflicts = []

    for line in output.splitlines():
        line = line.strip()
        if line.startswith("*") or "conflict" in line.lower():
            conflicts.append(line)

    return {
        "installed": False,
        "can_install": len(conflicts) == 0,
        "conflicts": conflicts,
    }
